# Generated by Django 2.2.5 on 2020-11-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=99)),
                ('option', models.CharField(max_length=99)),
                ('parameterfixed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traindata', models.BinaryField(null=True)),
                ('testdata', models.BinaryField(null=True)),
                ('cvdata', models.BinaryField(null=True)),
                ('originaldataset', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('noofepochs', models.IntegerField(null=True)),
                ('batchsize', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=99, null=True)),
                ('transition', models.IntegerField(null=True)),
                ('reformat', models.TextField(null=True)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('inputlayer', models.BooleanField(default=False)),
                ('outputlayer', models.BooleanField(default=False)),
                ('layertype', models.CharField(max_length=50)),
                ('configuration', models.ManyToManyField(to='mysite.Configuration')),
                ('inputlayers', models.ManyToManyField(related_name='_layer_inputlayers_+', to='mysite.Layer')),
            ],
        ),
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='NeuralNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layers', models.ManyToManyField(to='mysite.Layer')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epochno', models.IntegerField()),
                ('configuration', models.ManyToManyField(to='mysite.Configuration')),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_loss', models.DecimalField(decimal_places=4, max_digits=99)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.FloatField(max_length=50)),
                ('batch', models.IntegerField()),
                ('source', models.IntegerField()),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Result')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_text', models.CharField(max_length=9999, null=True)),
                ('author', models.CharField(max_length=100)),
                ('datacreated', models.DateField()),
                ('projectname', models.CharField(max_length=200)),
                ('input', models.CharField(max_length=250)),
                ('selectstatement', models.TextField(null=True)),
                ('udfclasses', models.TextField(null=True)),
                ('appendFeature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Feature')),
                ('datamodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.DataModels')),
                ('features', models.ManyToManyField(related_name='features', to='mysite.Feature')),
                ('neuralnetwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.NeuralNetwork')),
                ('projectstatistics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.Statistics')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='target', to='mysite.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterFixation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.ManyToManyField(related_name='configuration', to='mysite.Configuration')),
                ('parameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Configuration')),
            ],
        ),
        migrations.CreateModel(
            name='Optimizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('configuration', models.ManyToManyField(to='mysite.Configuration')),
            ],
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='optimizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.Optimizer'),
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='LayerWeights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('weights', models.CharField(max_length=999)),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Experiment')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='loss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.Loss'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='parameters',
            field=models.ManyToManyField(to='mysite.ParameterFixation'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Project'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='setup',
            field=models.ManyToManyField(to='mysite.CallbackSetup'),
        ),
        migrations.AddField(
            model_name='callbacksetup',
            name='configuration',
            field=models.ManyToManyField(to='mysite.Configuration'),
        ),
    ]
