# Generated by Django 3.1.3 on 2020-11-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='dimension',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
