# Generated by Django 3.1.3 on 2020-12-05 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_feature_dimension'),
    ]

    operations = [
        migrations.CreateModel(
            name='UDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=350)),
                ('udfexecutiontext', models.TextField()),
                ('outputtype', models.CharField(max_length=350)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.project')),
            ],
        ),
    ]
