# Generated by Django 3.1.3 on 2020-12-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_udf'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='configuration',
            field=models.ManyToManyField(to='mysite.Configuration'),
        ),
    ]
