# Generated by Django 3.1.3 on 2020-12-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_project_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='targets',
            field=models.ManyToManyField(related_name='targets', to='mysite.Feature'),
        ),
    ]
